import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LandingNav from "@/components/shared/navBars/LandingNav";

const RocknRollOne = localFont({
  src: "./fonts/RocknRollOne-Regular.ttf",
  variable: "--font-geist-sans",
});
const Urbanist = localFont({
  src: "./fonts/Urbanist-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${Urbanist.className} ${RocknRollOne.className} antialiased bg-black text-white`}
      >
        <header>
          <LandingNav />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
